# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 725a3192afd8c42e889d53b8717085fe622e5abb4b2150af806e983f98a944abbec3cc92bd04ea6c18cf4689bb77b440097aa5ae7d78fd4440648444baf71baa

test:
  secret_key_base: d4fc75765bd0a1e37bbdba1d38dbf744fec1286515d112d5b5e5ed8b19f693d95a0e24f59e6fc5aa49a6bc12e9b080398bc665084165bcae39564afe73b817de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
